# Generated by Django 3.2.12 on 2022-02-28 05:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('national_code', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('birth_day', models.DateField()),
                ('usr_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bed', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('special_view_flag', models.BooleanField(default=False)),
                ('max_num_person', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('cost_per_night', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reservation_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('reservation_status', models.CharField(choices=[('1', 'active'), ('2', 'checkout'), ('3', 'fin')], default='1', max_length=1)),
                ('reservation_customer_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_app.customer_info')),
                ('reservation_room_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.room')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('1', 'succecfull'), ('2', 'rejected')], default='1', max_length=1)),
                ('payment_amount', models.DecimalField(decimal_places=3, max_digits=8)),
                ('payment_reservation_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Dependent_info',
            fields=[
                ('dependent_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('national_code', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('dependent_customer_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.customer_info')),
            ],
        ),
    ]
